### ISSUE TITLE
Using java objects in conditions with "or"

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/skript-reflect#59]
**Describe the bug**
When you try to compare an object with more than one java objects condition fails.

**To reproduce**
```
set {_ice} to Material.ICE
if {_ice} is (Material.ICE or Material.STONE):
  broadcast "ICE"
else:
  broadcast "NOT ICE"
```

**Expected behavior**
Using javaobjects with skript's conditions properly.

**Server information**
- skript-reflect: 2.3
- Skript: 2.6.3
- Bukkit: Purpur-1770
- Minecraft: 1.19.2
- Java: 17
- OS: CentOS 7

**Additional context**
I know you can simply replace `if {_ice} is (Material.ICE or Material.STONE):` with `if (Material.ICE and Material.STONE) contains {_ice}:`
but that's totally different condition.

**Comment by Lotzyprod** [comment]
Yes, I also encountered this bug, I solved it in the same way as the author

**Comment by TPGamesNL** [comment]
This occurs because Skript parses the input as `if {_ice} is ((Material.ICE or Material).STONE)` (i.e. gets the `STONE` field of `Material.ICE or MATERIAL`). You can add parentheses as such: `(Material.ICE) and (Material.STONE)`.

I don't think I can / should do anything about this. Although it doesn't make much sense with the context of Material class and these fields, in general this could be desired.

Same in terms of the Skript side of this, I don't think the parser should be changed. It currently prefers a single expression over a list of expressions, which causes this behaviour.
