### ISSUE TITLE
Custom event with priority doesn't work

### ISSUE THREAD

**Issue by eiqq** [SkriptLang/skript-reflect#65]
**Describe the bug**

Custom event with priority does not work.
without priority, it works.
ex)
on castskill with priority monitor:
	broadcast "!"                           <--- errors

on castskill:
	broadcast "!"   <--- work

on the skript 2.6.4 with skript-reflect 2.3, both codes above was working

**Screenshots**
![2023-03-28_00 17 27](https://user-images.githubusercontent.com/79748558/228158504-4c183ee8-1a02-4c0d-ad02-0362f28b1de3.png)

**Server information**
- skript-reflect: 2.3   (using addonpathcer)
- Skript: 2.7.0 - beta2
- Bukkit: Purpur
- Minecraft: 1.19.4
- Java: 17
- OS: Windows 11
 
**Additional context**

**Comment by TPGamesNL** [comment]
Skript adds the syntax for event priorities during registration (`Skript.registerEvent`), but skript-reflect's custom events are registered differently (an event without patterns is registered when the addon is loaded, and patterns are added when a custom event is being parsed).

Can probably be fixed by manually adding the priority suffix to patterns from custom events

**Comment by TPGamesNL** [comment]
Fixed in https://github.com/TPGamesNL/skript-reflect/commit/0abbe26b580017d23a04398cd2a33c5b69908897
